CREATE TABLE CLIENTS (
    NUMCLI INT(5) PRIMARY KEY,
    NOM VARCHAR(10) , 
    PRENOM VARCHAR(10) , 
    EMAIL VARCHAR(10) UNIQUE , 
    NUMT VARCHAR(8)
);

CREATE TABLE VOYAGE (
    CODEVOYAGE INT(5) PRIMARY KEY, 
    DESTINA VARCHAR(10), 
    DUREE INT(2) , 
    PRIX DECIMAL(5,2) 
);

CREATE TABLE RESERVATION (
    NUMCLI INT(5) PRIMARY KEY, 
    CODEVOYAGE INT(5) PRIMARY KEY, 
    DATERES DATE ,
    CONSTRAINT NCLIKEY FOREIGN KEY (NUMCLI) REFERENCES CLIENTS(NUMCLI) ,
    CONSTRAINT CODEVKEY FOREIGN KEY(CODEVOYAGE) REFERENCES VOYAGE(CODEVOYAGE)
);



SELECT NOM , PRENOM , EMAIL FROM CLIENTS WHERE WHERE NUMCLI IN (SELECT NUMCLI FROM RESERVATION ) ; 

SELECT NOM, PRENOM, EMAIL FROM CLIENTS WHERE NUMCLI NOT IN (SELECT NUMCLI FROM RESERVATION);

SELECT V.DESTINATION, C.NOM, C.PRENOM FROM VOYAGE V, CLIENTS C , RESERVATION R WHERE V.DUREE >=  10 AND PRIX < 1000 AND R.NUMCLI = C.NUMCLI AND V.CODEVOYAGE = R.CODEVOYAGE;

CREATE OR REPLACE PROCEDURE RESERVED() IS 
DECLARE 
TOTALTRIPT INT(5)
BEGIN 
    TOTALTRIPS := 0;

    --COUNT TOTAL TRIPS 
    DBMS_OUTPUT.PUT_LINE('CLIENTS WHO RESERVED IN EVERY TRIP \N');
    FOR ROWW IN (SELECT NUMCLI FROM CLIENTS )
        --TAKE THE CLIENT ID 
        FOR RR IN (SELECT * FROM RESERVATION ) 
            IF ROWW.NUMCLI = RR.NUMCLI THEN 
                TOTALTRIPS := TOTALTRIPS +1 ;
            END IF ;
        END FOR ; 
        IF TOTALTRIPS = (SELECT COUNT(*) FROM VOYAGES)  THEN
            DBMS_OUTPUT.PUT_LINE('NAME : ' || ROWW.NOM || ' LAST NAME :' || ROWW.PRENOM || 'EMAIL : ' || ROWW.EMAIL || 'PHONE : '  || ROWW.NUMT );
        END IF ;
        TOTALTRIPS := 0; 
    END FOR ; 
END;




--WE GET BY THE ID
CREATE OR REPLACE FINDCLIENT (IDEN INT(5)) IS 
BEGIN

    FOR T IN (SELECT * FROM CLIENTS) 
        IF CLIENTS.CODECLI = IDEN THEN
            DBMS_OUTPUT.PUT_LINE('NAME : ' || T.NOM || ' LAST NAME :' || T.PRENOM || 'EMAIL : ' || T.EMAIL || 'PHONE : '  || T.NUMT );
        END IF 
    END FOR 
END  ; 





